FROM oven/bun:1 AS builder  
WORKDIR /app  
COPY package.json bun.lock ./ 
RUN bun install --frozen-lockfile  
COPY . .  
ENV NODE_ENV=production
RUN bun run build  
LABEL org.opencontainers.image.source=https://github.com/rushilcodes/portfolio
LABEL org.opencontainers.image.description="Rushil's Portfolio"


FROM gcr.io/distroless/nodejs22:nonroot AS runner  
WORKDIR /app  
COPY --from=builder /app/dist ./dist  
COPY --from=builder /app/package.json ./  
COPY --from=builder /app/bun.lock ./  
RUN npm install -g bun
EXPOSE 3000  
CMD ["bun", "run", "preview"]  
LABEL org.opencontainers.image.source=https://github.com/rushilcodes/portfolio
LABEL org.opencontainers.image.description="Rushil's Portfolio"

