FROM node:23-alpine AS builder  
WORKDIR /app  
COPY package.json bun.lock ./ 
RUN npm install -g bun
RUN bun install --frozen-lockfile  
COPY . .  
RUN bun run build  

FROM gcr.io/distroless/nodejs18 AS runner  
WORKDIR /app  
RUN adduser --system --no-create-home nodeuser  
USER nodeuser  
COPY --from=builder /app/dist ./dist  
COPY --from=builder /app/package.json ./  
COPY --from=builder /app/bun.lockb ./  
EXPOSE 3000  
CMD ["bun", "run", "preview"]  
