FROM oven/bun AS builder  
WORKDIR /app  
COPY package.json bun.lock ./  
RUN bun install --frozen-lockfile  
COPY . .  
RUN bun run build  

FROM gcr.io/distroless/nodejs18:nonroot AS runner  
WORKDIR /app  
USER nodeuser  
COPY --from=builder /app/dist ./dist  
COPY --from=builder /app/package.json ./  
COPY --from=builder /app/bun.lockb ./  
EXPOSE 50051  
CMD ["bun", "run", "start"]
