name: Build, Push, and Slim Docker Images

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build_and_slim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---- Build and Push Client Image ----
      - name: Build Client Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/client:latest ./client
      - name: Push Client Image
        run: |
          docker push ghcr.io/${{ github.repository }}/client:latest

      # ---- Build and Push Server Image ----
      - name: Build Server Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/server:latest ./server
      - name: Push Server Image
        run: |
          docker push ghcr.io/${{ github.repository }}/server:latest

      # ---- Install docker-slim ----
      - name: Install docker-slim
        run: |
          curl -sL https://downloads.docker-slim.com/releases/1.39.0/dist_linux.tar.gz | tar xz
          sudo mv docker-slim /usr/local/bin/docker-slim

      # ---- Slim Client Image ----
      - name: Slim Client Image
        run: |
          docker-slim build --tag ghcr.io/${{ github.repository }}/client:slim ghcr.io/${{ github.repository }}/client:latest
      - name: Push Slim Client Image
        run: |
          docker push ghcr.io/${{ github.repository }}/client:slim

      # ---- Slim Server Image ----
      - name: Slim Server Image
        run: |
          docker-slim build --tag ghcr.io/${{ github.repository }}/server:slim ghcr.io/${{ github.repository }}/server:latest
      - name: Push Slim Server Image
        run: |
          docker push ghcr.io/${{ github.repository }}/server:slim

